//! Protocol-aware start-session dispatcher.
//!
//! Claude and Codex keep using `commands::session`. Pi and Grok create dedicated
//! actors that are inserted into the same `ActorSessionMap`, so every operation
//! after startup uses the existing SessionActor command surface.

use crate::agent::adapter::{self, ActorSessionMap};
use crate::agent::grok_session_actor;
use crate::agent::pi_session_actor;
use crate::agent::runtime_providers::RuntimeProviderAdapter;
use crate::agent::session_actor::{ActorCommand, AttachmentData};
use crate::agent::session_protocol::CodexSkillRef;
use crate::agent::spawn_locks::SpawnLocks;
use crate::models::{BusEvent, ExecutionPath, RunStatus, SessionMode};
use crate::storage;
use crate::web_server::broadcaster::BroadcastEmitter;
use crate::work::runtime::{WorkBridgeLaunchInfo, WorkRuntimeLaunchStage, WorkRuntimeLaunchTrace};
use std::collections::HashMap;
use std::sync::Arc;
use tauri::State;
use tokio_util::sync::CancellationToken;

// Tauri 2.5 generates a crate-global `__cmd__<function>` macro for every
// `#[tauri::command]`. Defining another command with the same Rust function
// name in this module therefore collides with commands::session. The public
// functions below intentionally have no command attribute and reuse the
// wrapper macros generated by commands::session; their signatures match.
pub use super::session::{
    __cmd__cancel_session_turn, __cmd__send_session_control, __cmd__send_session_message,
    __cmd__start_session, __cmd__steer_session_message, __cmd__stop_session,
};

async fn get_cmd_tx(
    sessions: &ActorSessionMap,
    run_id: &str,
) -> Result<tokio::sync::mpsc::Sender<ActorCommand>, String> {
    let map = sessions.lock().await;
    map.get(run_id)
        .map(|handle| handle.cmd_tx.clone())
        .ok_or_else(|| format!("Session {} not found", run_id))
}

pub(crate) async fn stop_actor(
    sessions: &ActorSessionMap,
    run_id: &str,
    reason: crate::agent::session_actor::RuntimeStopReason,
) -> Result<super::session::StopActorOutcome, String> {
    super::session::stop_actor(sessions, run_id, reason).await
}

fn pi_adapter_settings(
    run: &crate::models::RunMeta,
    permission_mode_override: Option<&str>,
) -> crate::agent::adapter::AdapterSettings {
    let agent_settings = storage::settings::get_agent_settings(&run.agent);
    let user_settings = storage::settings::get_user_settings();
    let mut settings =
        adapter::build_adapter_settings(&agent_settings, &user_settings, run.model.clone());
    if run.effort.is_some() {
        settings.effort = run.effort.clone();
    } else if run.app_mode == crate::work::models::AppMode::Code && !run.code_standalone_task {
        if let Ok(project) =
            storage::project_preferences::get(&run.cwd, run.remote_host_name.as_deref(), &run.agent)
        {
            if project.effort.is_some() {
                settings.effort = project.effort;
            }
            if permission_mode_override.is_none() && project.permission_mode.is_some() {
                settings.permission_mode = project.permission_mode;
            }
        }
    }
    adapter::append_continuation_context(&mut settings, run.continuation_context.as_deref());
    if let Some(mode) = permission_mode_override.filter(|mode| !mode.trim().is_empty()) {
        // Never persist Pi's permission mode. AgentCabin supplies the mode for
        // this process only, so a new chat starts from the safe default again.
        settings.permission_mode = Some(mode.to_string());
    }
    settings
}

pub(crate) async fn pi_launch_context(
    run: &crate::models::RunMeta,
    permission_mode_override: Option<&str>,
) -> Result<
    (
        crate::agent::adapter::AdapterSettings,
        HashMap<String, String>,
    ),
    String,
> {
    let mut settings = pi_adapter_settings(run, permission_mode_override);
    if run.app_mode == crate::work::models::AppMode::Code {
        let display_guidance = include_str!("../agent/conversation-display.md");
        // Pi's --system-prompt takes precedence over --append-system-prompt.
        let prompt = if let Some(custom) = settings
            .system_prompt
            .as_mut()
            .filter(|prompt| !prompt.trim().is_empty())
        {
            custom
        } else {
            settings
                .append_system_prompt
                .get_or_insert_with(String::new)
        };
        prompt.push_str("\n\n");
        prompt.push_str(display_guidance);
        prompt.push_str(
            "\n\n## Todo 完成状态\n多步任务使用 Pi 的 todo 工具维护可见进度。创建任务后立即开始第一项：调用 todo(action=\"update\", id=<任务ID>, status=\"in_progress\")；每项工作完成后立即调用 todo(action=\"update\", id=<任务ID>, status=\"completed\")，再开始下一项。所有工作和成果写入完成后、发送最终答复之前，必须调用 todo(action=\"list\") 读取当前任务及 ID，再逐项把确已完成的任务更新为 completed，最后再次 list 核对；不要仅凭文字汇报完成。仍未完成或受阻的任务保持 pending/in_progress，并说明原因。不要把 Work 计划工具 work_update_step 当成 Pi Todo 状态更新。",
        );
    }
    let mut extra_env = HashMap::new();
    let shared_skills_root = crate::storage::profile_bindings::shared_skills_dir();
    extra_env.insert(
        "AGENTCABIN_SHARED_SKILLS_DIR".to_string(),
        shared_skills_root.to_string_lossy().into_owned(),
    );

    // Sync configured Pi Code MCP servers into ~/.agentcabin/profiles/code/pi/mcp.json
    if let Err(e) = crate::storage::profile_bindings::sync_pi_code_mcp_from_catalog_and_bindings(
        (!run.code_standalone_task).then_some(run.cwd.as_str()),
    ) {
        log::warn!(
            "[session_dispatch] failed to sync Pi Code MCP bindings: {}",
            e
        );
    }
    let shared_paths = crate::work::paths::WorkPaths::app();
    shared_paths.ensure_layout()?;
    crate::work::system_packages::ensure_pi_interaction_packages(&shared_paths).await?;
    let pi_ask_user_question = crate::work::system_packages::common_system_package_entry_path(
        &shared_paths,
        crate::work::system_packages::PI_ASK_USER_QUESTION_PACKAGE_NAME,
    );
    let pi_todo = crate::work::system_packages::common_system_package_entry_path(
        &shared_paths,
        crate::work::system_packages::PI_TODO_PACKAGE_NAME,
    );
    let code_desktop_adapter = if run.app_mode == crate::work::models::AppMode::Code
        && crate::work::desktop_operator::is_enabled()
    {
        Some(crate::work::resources::ensure_code_desktop_operator_adapter(&shared_paths)?)
    } else {
        None
    };
    let context_usage_adapter =
        crate::pi_context_runtime::ensure_context_usage_extension(&shared_paths)?;
    let connector_skill_sources =
        crate::work::connector_package_manager::package_skill_sources(&shared_paths)?;
    let connector_cli_enabled =
        crate::work::connector_package_manager::list_with_paths(&shared_paths)?
            .into_iter()
            .any(|package| {
                package
                    .manifest
                    .runtimes
                    .contains(&crate::work::connector_package::ConnectorRuntimeKind::Cli)
                    && package.state.trusted
                    && package.state.enabled
            });
    let code_connector_adapter = if connector_cli_enabled {
        Some(crate::code_connector_runtime::ensure_code_adapter(
            &shared_paths,
        )?)
    } else {
        None
    };
    if code_connector_adapter.is_some() {
        extra_env.insert(
            "AGENTCABIN_CODE_CONNECTOR_ENABLED".to_string(),
            "1".to_string(),
        );
    }
    let code_mcp_enabled = crate::storage::profile_bindings::project_mcp_bindings_from_catalog(
        &crate::storage::data_dir(),
    )
    .0
    .iter()
    .any(|server| server.enabled);
    if code_mcp_enabled {
        crate::work::system_packages::ensure_common_system_package(
            &shared_paths,
            crate::work::system_packages::PI_MCP_ADAPTER_PACKAGE_NAME,
            crate::work::system_packages::PI_MCP_ADAPTER_VERSION,
            crate::work::system_packages::PI_MCP_ADAPTER_SOURCE,
        )
        .await?;
    }
    let (browser_config, browser_api_key) = crate::work::browser::runtime(&shared_paths)?;
    let web_access_enabled =
        browser_config.enabled && crate::storage::profile_bindings::is_web_access_enabled();
    let browser_use_enabled = crate::storage::profile_bindings::is_browser_use_enabled();
    let mut shared_browser_adapters: Option<(std::path::PathBuf, std::path::PathBuf)> = None;
    if web_access_enabled || browser_use_enabled {
        let (web_adapter, browser_adapter) =
            crate::browser_runtime::ensure_code_adapters(&shared_paths)?;
        shared_browser_adapters = Some((web_adapter, browser_adapter));
        extra_env.insert("AGENTCABIN_BROWSER_ENABLED".to_string(), "1".to_string());
        extra_env.insert("AGENTCABIN_BROWSER_SESSION_ID".to_string(), run.id.clone());
        if !browser_config.allowed_hosts.is_empty() {
            extra_env.insert(
                "AGENTCABIN_BROWSER_ALLOWED_HOSTS".to_string(),
                browser_config.allowed_hosts.join(","),
            );
        }
    }
    if web_access_enabled {
        let browser_run_dir = storage::run_dir(&run.id).join("browser");
        extra_env.insert("AGENTCABIN_WEB_ENABLED".to_string(), "1".to_string());
        extra_env.insert(
            "AGENTCABIN_WEB_PROVIDER".to_string(),
            browser_config.provider.clone(),
        );
        if let Some(endpoint) = browser_config.endpoint_url.as_ref() {
            extra_env.insert("AGENTCABIN_WEB_ENDPOINT_URL".to_string(), endpoint.clone());
        }
        extra_env.insert(
            "AGENTCABIN_WEB_MAX_RESULTS".to_string(),
            browser_config.max_results.to_string(),
        );
        extra_env.insert(
            "AGENTCABIN_WEB_RUN_DIR".to_string(),
            browser_run_dir.to_string_lossy().into_owned(),
        );
        if !browser_config.allowed_hosts.is_empty() {
            extra_env.insert(
                "AGENTCABIN_WEB_ALLOWED_HOSTS".to_string(),
                browser_config.allowed_hosts.join(","),
            );
        }
        if let Some(api_key) = browser_api_key.as_ref() {
            extra_env.insert("AGENTCABIN_WEB_API_KEY".to_string(), api_key.clone());
            extra_env.insert("AGENTCABIN_WEB_TAVILY_API_KEY".to_string(), api_key.clone());
        }
        let code_proxy_env = crate::work::proxy::work_node_proxy_env();
        extra_env.extend(code_proxy_env);
    }
    let caps = crate::agent::capability_resolver::CapabilityResolver::resolve(
        &crate::storage::data_dir(),
        crate::work::models::AppMode::Code,
        crate::agent::capability_resolver::RuntimeProviderKind::Pi,
        &run.cwd,
        &run.id,
    )
    .await?;
    let adapter = crate::agent::runtime_providers::pi::PiRuntimeAdapter;
    adapter::append_continuation_context(&mut settings, Some(&caps.capability_guidance()));
    let _ = adapter.prepare_runtime(&caps)?;
    let _ = crate::work::capability_projection::record_launch_snapshot(
        &caps,
        &caps.managed_runtime_dir,
    );
    settings.pi_code_profile_dir = Some(caps.managed_runtime_dir.to_string_lossy().into_owned());
    settings.pi_shared_extension_sources =
        crate::storage::profile_bindings::list_enabled_pi_extension_sources("code")
            .into_iter()
            .filter(|path| {
                let name = path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap_or_default();
                name != crate::work::system_packages::PI_MCP_ADAPTER_PACKAGE_NAME
                    && name != crate::work::system_packages::PI_WEB_ACCESS_PACKAGE_NAME
                    && !crate::work::system_packages::is_pi_interaction_source(
                        &path.to_string_lossy(),
                    )
            })
            .map(|path| path.to_string_lossy().into_owned())
            .collect();
    settings
        .pi_shared_extension_sources
        .push(context_usage_adapter.to_string_lossy().into_owned());
    if code_mcp_enabled {
        settings.pi_shared_extension_sources.push(
            crate::work::system_packages::common_system_package_entry_path(
                &shared_paths,
                crate::work::system_packages::PI_MCP_ADAPTER_PACKAGE_NAME,
            )
            .to_string_lossy()
            .into_owned(),
        );
    }
    if web_access_enabled || browser_use_enabled {
        if let Some((web_adapter, browser_adapter)) = shared_browser_adapters {
            if web_access_enabled {
                settings
                    .pi_shared_extension_sources
                    .push(web_adapter.to_string_lossy().into_owned());
            }
            if browser_use_enabled {
                settings
                    .pi_shared_extension_sources
                    .push(browser_adapter.to_string_lossy().into_owned());
            }
        }
    }
    if let Some(adapter) = code_desktop_adapter {
        settings
            .pi_shared_extension_sources
            .push(adapter.to_string_lossy().into_owned());
    }
    if let Some(adapter) = code_connector_adapter {
        settings
            .pi_shared_extension_sources
            .push(adapter.to_string_lossy().into_owned());
    }
    settings
        .pi_shared_extension_sources
        .push(pi_ask_user_question.to_string_lossy().into_owned());
    settings
        .pi_shared_extension_sources
        .push(pi_todo.to_string_lossy().into_owned());
    let mut code_skills = crate::storage::profile_bindings::list_enabled_skill_paths()
        .into_iter()
        .map(|p| p.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    for source in connector_skill_sources {
        if !code_skills.contains(&source) {
            code_skills.push(source);
        }
    }
    let connector_catalog = crate::storage::profile_bindings::read_connector_catalog();
    for cat in connector_catalog {
        if crate::storage::profile_bindings::is_connector_enabled(&cat.id) {
            let pkg_skills = crate::storage::data_dir()
                .join("connectors")
                .join("catalog")
                .join(&cat.id)
                .join("skills");
            if pkg_skills.is_dir() {
                if let Ok(entries) = std::fs::read_dir(&pkg_skills) {
                    for entry in entries.flatten() {
                        let p = entry.path();
                        if p.is_dir() && p.join("SKILL.md").is_file() {
                            let p_str = p.to_string_lossy().into_owned();
                            if !code_skills.contains(&p_str) {
                                code_skills.push(p_str);
                            }
                        }
                    }
                }
            }
        }
    }
    settings.pi_work_skill_sources = code_skills;

    Ok((settings, extra_env))
}

fn normalize_grok_permission_mode(mode: Option<String>) -> Result<Option<String>, String> {
    let Some(raw) = mode else {
        return Ok(None);
    };
    let mode = raw.trim();
    if mode.is_empty() {
        return Ok(None);
    }
    match mode {
        "default" | "acceptEdits" | "bypassPermissions" | "auto" | "dontAsk" | "plan" => {
            Ok(Some(mode.to_string()))
        }
        _ => Err(format!("Unsupported Grok permission mode: {mode}")),
    }
}

fn emit_state(emitter: &Arc<BroadcastEmitter>, run_id: &str, state: &str, error: Option<String>) {
    emitter.persist_and_emit(
        run_id,
        &BusEvent::RunState {
            run_id: run_id.to_string(),
            state: state.to_string(),
            exit_code: None,
            error,
        },
    );
}

async fn fail_work_session_launch(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    run_id: &str,
    bridge_token: Option<&str>,
    error: String,
) -> Result<(), String> {
    let superseded = if let Some(token) = bridge_token {
        let map = sessions.lock().await;
        map.get(run_id)
            .and_then(|handle| handle.work_bridge_token.as_deref())
            .is_some_and(|active_token| active_token != token)
    } else {
        false
    };

    // Only release the lease created by this launch. A WorkRun can be resumed
    // while an older actor is still finishing cleanup; revoking by WorkRun id
    // would also invalidate the replacement actor's fresh token.
    if let Some(token) = bridge_token {
        crate::work::internal_bridge::revoke_session_token(token).await;
    }
    if superseded {
        log::debug!(
            "[session_dispatch] ignoring stale Work launch failure for replaced actor: run_id={}",
            run_id
        );
        return Err(error);
    }
    crate::browser_runtime::revoke_session(run_id).await;
    storage::runs::update_status(run_id, RunStatus::Failed, None, Some(error.clone())).ok();
    emit_state(emitter, run_id, "failed", Some(error.clone()));
    Err(error)
}

async fn prepare_work_runtime(
    adapter: &dyn crate::work::runtime::WorkRuntimeAdapter,
    context: crate::work::runtime::WorkRuntimePrepareContext,
) -> Result<(), String> {
    let provider = adapter.provider();
    let capabilities = context.capabilities.clone();
    adapter
        .prepare_runtime(&context)
        .await
        .map_err(String::from)?;

    // Keep the shared managed-runtime projection provider-aware while leaving
    // Work package/MCP provisioning behind the Work adapter above.
    let provider_adapter = crate::agent::runtime_providers::get_adapter(provider);
    provider_adapter.prepare_runtime(&capabilities)?;
    Ok(())
}

/// Assemble the authoritative plan for one Work turn from the current durable run state.
///
/// Every path that sends a message after actor startup uses this helper before enqueueing the
/// actor command. The resulting plan is then carried by that command, so the actor never has to
/// infer which shared on-disk snapshot belongs to a queued message.
pub(crate) async fn assemble_work_context_plan_for_turn(
    run: &crate::models::RunMeta,
    prompt: &str,
) -> Result<crate::work::context::WorkContextPlan, String> {
    if run.app_mode != crate::work::models::AppMode::Work {
        return Err("Work Context Plan requested for a non-Work run".to_string());
    }

    let work_paths = crate::work::paths::WorkPaths::app();
    let provider =
        crate::agent::capability_resolver::RuntimeProviderKind::try_from_agent_str(&run.agent)
            .map_err(|error| format!("Invalid Work runtime provider: {error}"))?;
    crate::work::runtime::get_pi_work_runtime(&run.agent).map_err(String::from)?;
    let capabilities = crate::agent::capability_resolver::CapabilityResolver::resolve(
        &crate::storage::data_dir(),
        crate::work::models::AppMode::Work,
        provider,
        &run.cwd,
        &run.id,
    )
    .await
    .map_err(|error| format!("Capability resolution failed: {error}"))?;
    let task_state = crate::work::task_state::load(&run.id)
        .map_err(|error| format!("Task state read failed: {error}"))?;

    let custom_rules = if let Some(ws_id) = &run.workspace_id {
        if let Ok(ws) = crate::work::workspace::manager().get(ws_id) {
            let context_agents = std::path::Path::new(&ws.context_dir).join("AGENTS.md");
            let root_agents = std::path::Path::new(&ws.root).join("AGENTS.md");
            if context_agents.is_file() {
                std::fs::read_to_string(context_agents).ok()
            } else if root_agents.is_file() {
                std::fs::read_to_string(root_agents).ok()
            } else {
                let rules_file = work_paths.work_profile_dir().join("AGENTS.md");
                std::fs::read_to_string(rules_file).ok()
            }
        } else {
            let rules_file = work_paths.work_profile_dir().join("AGENTS.md");
            std::fs::read_to_string(rules_file).ok()
        }
    } else {
        None
    };

    let input = crate::work::context::WorkContextAssemblyInput {
        app_mode: crate::work::models::AppMode::Work,
        runtime: provider,
        run_id: run.id.clone(),
        session_id: run.session_id.clone(),
        workspace_id: run.workspace_id.clone(),
        task_id: run.work_task_id.clone(),
        preset: run.work_preset,
        execution_context: run.work_execution_context,
        prompt: Some(prompt.to_string()),
        workspace: run
            .workspace_id
            .as_deref()
            .and_then(|ws_id| crate::work::workspace::manager().get(ws_id).ok()),
        task_state,
        task: run.work_task_id.as_deref().and_then(|task_id| {
            crate::work::tasks::TaskManager::new(work_paths.clone())
                .get_task(task_id)
                .ok()
        }),
        capabilities,
        artifacts: run
            .workspace_id
            .as_deref()
            .map(|ws_id| crate::work::artifacts::list(ws_id, Some(&run.id)).unwrap_or_default())
            .unwrap_or_default(),
        library_items: crate::work::library::LibraryManager::new(work_paths)
            .list_items(run.workspace_id.as_deref(), None, None)
            .unwrap_or_default(),
        custom_rules,
    };

    Ok(crate::work::context::WorkContextAssembler::assemble(input))
}

#[allow(clippy::too_many_arguments)]
async fn start_grok_session(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    spawn_locks: &SpawnLocks,
    cancel_token: &CancellationToken,
    run: crate::models::RunMeta,
    mode: Option<SessionMode>,
    session_id: Option<String>,
    initial_message: Option<String>,
    attachments: Option<Vec<AttachmentData>>,
    permission_mode_override: Option<String>,
    skills: Option<Vec<CodexSkillRef>>,
) -> Result<(), String> {
    let run_id = run.id.clone();
    let _guard = spawn_locks.acquire(&run_id).await;
    if run.resolved_execution_path() != ExecutionPath::SessionActor {
        return Err(format!(
            "Grok ACP requires execution_path=session_actor for run {}",
            run_id
        ));
    }
    if run.remote_host_name.is_some() || run.remote_cwd.is_some() {
        return Err("Grok ACP session transport does not support remote hosts yet".to_string());
    }
    let permission_mode_override = normalize_grok_permission_mode(permission_mode_override)?;

    let session_mode = mode.unwrap_or_default();
    if matches!(&session_mode, SessionMode::Fork) {
        return Err("Fork mode is not supported by the Grok ACP MVP".to_string());
    }
    let resume_session_id = match &session_mode {
        SessionMode::Resume | SessionMode::Continue => Some(
            session_id
                .or_else(|| run.session_id.clone())
                .ok_or_else(|| "Grok session_id is required for resume/continue".to_string())?,
        ),
        SessionMode::New => session_id.or_else(|| run.session_id.clone()),
        SessionMode::Fork => unreachable!(),
    };

    log::debug!(
        "[session_dispatch] Grok start: run_id={}, mode={:?}, resume={:?}, skills={}",
        run_id,
        session_mode,
        resume_session_id,
        skills.as_ref().map_or(0, |s| s.len())
    );
    emit_state(emitter, &run_id, "spawning", None);
    storage::runs::update_status(&run_id, RunStatus::Running, None, None).ok();

    let replaced = super::session::stop_actor(
        sessions,
        &run_id,
        crate::agent::session_actor::RuntimeStopReason::Superseded,
    )
    .await?
    .was_active;
    if replaced {
        log::debug!(
            "[session_dispatch] replaced existing Grok actor for run_id={}",
            run_id
        );
    }

    let resumes_existing_session = resume_session_id.is_some();
    // Work runs return through the first-level Work runtime dispatch before
    // reaching this Code-only provider path.
    let app_mode = crate::work::models::AppMode::Code;
    let desktop_runtime = if crate::work::desktop_operator::is_enabled() {
        Some(crate::desktop_runtime::register_session(&run_id).await?)
    } else {
        None
    };
    let cmd_tx = match grok_session_actor::spawn_actor(
        Arc::clone(emitter),
        sessions.clone(),
        run_id.clone(),
        run.cwd.clone(),
        run.model.clone(),
        resume_session_id,
        run.continuation_context.clone(),
        permission_mode_override,
        cancel_token.clone(),
        app_mode,
        desktop_runtime,
    )
    .await
    {
        Ok(sender) => sender,
        Err(error) => {
            crate::browser_runtime::revoke_session(&run_id).await;
            crate::desktop_runtime::revoke_session(&run_id).await;
            storage::runs::update_status(&run_id, RunStatus::Failed, None, Some(error.clone()))
                .ok();
            emit_state(emitter, &run_id, "failed", Some(error.clone()));
            return Err(error);
        }
    };

    let brand_new = matches!(&session_mode, SessionMode::New) && !resumes_existing_session;
    let initial_text = initial_message
        .or_else(|| brand_new.then(|| run.prompt.clone()))
        .filter(|text| !text.trim().is_empty());
    if let Some(text) = initial_text {
        let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
        cmd_tx
            .send(ActorCommand::SendMessage {
                text,
                attachments: attachments.unwrap_or_default(),
                skills: skills.unwrap_or_default(),
                work_context_plan: None,
                reply: reply_tx,
            })
            .await
            .map_err(|_| "Grok actor died before accepting the initial message".to_string())?;
        // The actor queues this command while ACP is still completing initialize /
        // session/new. Returning once it is queued lets the frontend open the run
        // immediately; user_message, running, and any startup failure continue to
        // arrive through the durable bus-event stream. Waiting for reply_rx here
        // made a cold Grok session block the whole chat navigation for several seconds.
        drop(reply_rx);
    }

    Ok(())
}

#[allow(clippy::too_many_arguments)]
async fn start_work_session_actor(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    spawn_locks: &SpawnLocks,
    cancel_token: &CancellationToken,
    run: crate::models::RunMeta,
    mode: Option<SessionMode>,
    session_id: Option<String>,
    initial_message: Option<String>,
    attachments: Option<Vec<AttachmentData>>,
    permission_mode_override: Option<&str>,
    skills: Option<Vec<CodexSkillRef>>,
    adapter: &dyn crate::work::runtime::WorkRuntimeAdapter,
    launch_overrides: Option<crate::work::runtime::WorkLaunchOverrides>,
) -> Result<(), String> {
    let run_id = run.id.clone();
    let _guard = spawn_locks.acquire(&run_id).await;
    if run.resolved_execution_path() != ExecutionPath::SessionActor {
        return Err(format!(
            "Work Runtime requires execution_path=session_actor for run {}",
            run_id
        ));
    }
    if run.remote_host_name.is_some() || run.remote_cwd.is_some() {
        return Err("Work Runtime session transport does not support remote hosts yet".to_string());
    }

    let session_mode = mode.unwrap_or_default();
    match &session_mode {
        SessionMode::Resume => {
            if !adapter.capabilities().supports_resume {
                return Err(format!(
                    "Work Runtime '{}' does not support session resume",
                    adapter.provider().as_str()
                ));
            }
        }
        SessionMode::Continue => {
            if !adapter.capabilities().supports_continuation {
                return Err(format!(
                    "Work Runtime '{}' does not support session continuation",
                    adapter.provider().as_str()
                ));
            }
        }
        SessionMode::Fork => {
            return Err("Fork mode not supported in Work mode".to_string());
        }
        SessionMode::New => {}
    }

    let session_persistence_enabled = adapter
        .session_persistence_enabled(&run)
        .map_err(String::from)?;
    if matches!(&session_mode, SessionMode::Resume | SessionMode::Continue)
        && !session_persistence_enabled
    {
        return Err("Cannot resume: Work session persistence is disabled".to_string());
    }

    let work_paths = crate::work::paths::WorkPaths::app();
    // 1. Resolve capabilities once for the selected Work runtime.
    let caps = crate::agent::capability_resolver::CapabilityResolver::resolve(
        &crate::storage::data_dir(),
        crate::work::models::AppMode::Work,
        adapter.provider(),
        &run.cwd,
        &run.id,
    )
    .await?;

    // Record launch evidence snapshot for run inspector (unprivileged, zero secret values)
    let _ = crate::work::capability_projection::record_launch_snapshot(
        &caps,
        &caps.managed_runtime_dir,
    );

    // 2. Provision Work/runtime-specific state through the selected adapter.
    prepare_work_runtime(
        adapter,
        crate::work::runtime::WorkRuntimePrepareContext {
            paths: work_paths.clone(),
            run: run.clone(),
            capabilities: caps.clone(),
            context_plan: None,
        },
    )
    .await?;
    let mut launch_trace = WorkRuntimeLaunchTrace::default();
    launch_trace
        .record(WorkRuntimeLaunchStage::Prepared)
        .map_err(String::from)?;

    // 3. Setup internal bridge & proxy
    let (browser_config, _browser_api_key) = crate::work::browser::runtime(&work_paths)?;
    let work_proxy_env = if browser_config.enabled {
        crate::work::proxy::work_node_proxy_env()
    } else {
        HashMap::new()
    };
    let work_proxy_url = work_proxy_env.get("AGENTCABIN_WORK_PROXY_URL").cloned();
    let bridge_info = WorkBridgeLaunchInfo::from_run(&run, work_proxy_url)?;
    let state = match crate::work::task_state::load(&run_id) {
        Ok(state) => state,
        Err(error) => {
            return fail_work_session_launch(emitter, sessions, &run_id, None, error).await;
        }
    };
    if let Some(state) = state.as_ref() {
        for event in crate::work::task_state::bus_events(&run_id, state) {
            emitter.persist_and_emit(&run_id, &event);
        }
    }

    // 4. Assemble and persist the runtime-neutral WorkContextPlan
    let context_input = crate::work::context::WorkContextAssemblyInput {
        app_mode: crate::work::models::AppMode::Work,
        runtime: adapter.provider(),
        run_id: run_id.clone(),
        session_id: session_id.clone().or_else(|| run.session_id.clone()),
        workspace_id: run.workspace_id.clone(),
        task_id: run.work_task_id.clone(),
        preset: run.work_preset,
        execution_context: run.work_execution_context,
        prompt: initial_message
            .clone()
            .or_else(|| (!run.prompt.trim().is_empty()).then(|| run.prompt.clone())),
        workspace: run
            .workspace_id
            .as_deref()
            .and_then(|ws_id| crate::work::workspace::manager().get(ws_id).ok()),
        task_state: state,
        task: run.work_task_id.as_deref().and_then(|tid| {
            crate::work::tasks::TaskManager::new(work_paths.clone())
                .get_task(tid)
                .ok()
        }),
        capabilities: caps.clone(),
        artifacts: run
            .workspace_id
            .as_deref()
            .map(|ws_id| crate::work::artifacts::list(ws_id, Some(&run_id)).unwrap_or_default())
            .unwrap_or_default(),
        library_items: crate::work::library::LibraryManager::new(work_paths.clone())
            .list_items(run.workspace_id.as_deref(), None, None)
            .unwrap_or_default(),
        custom_rules: if let Some(ws_id) = &run.workspace_id {
            if let Ok(ws) = crate::work::workspace::manager().get(ws_id) {
                let context_agents = std::path::Path::new(&ws.context_dir).join("AGENTS.md");
                let root_agents = std::path::Path::new(&ws.root).join("AGENTS.md");
                if context_agents.is_file() {
                    std::fs::read_to_string(context_agents).ok()
                } else if root_agents.is_file() {
                    std::fs::read_to_string(root_agents).ok()
                } else {
                    let rules_file = work_paths.work_profile_dir().join("AGENTS.md");
                    std::fs::read_to_string(rules_file).ok()
                }
            } else {
                let rules_file = work_paths.work_profile_dir().join("AGENTS.md");
                std::fs::read_to_string(rules_file).ok()
            }
        } else {
            None
        },
    };
    let context_plan = crate::work::context::WorkContextAssembler::assemble(context_input);
    if let Err(err) = crate::work::context::save(&run_id, &context_plan) {
        return fail_work_session_launch(
            emitter,
            sessions,
            &run_id,
            None,
            format!("Work Context Plan 持久化或安全校验失败: {err}"),
        )
        .await;
    }
    emitter.persist_and_emit(
        &run_id,
        &crate::models::BusEvent::WorkContextPlanUpdated {
            run_id: run_id.clone(),
            plan: context_plan.clone(),
        },
    );

    emit_state(emitter, &run_id, "spawning", None);
    storage::runs::update_status(&run_id, RunStatus::Running, None, None).ok();

    let _had_session = match super::session::stop_actor(
        sessions,
        &run_id,
        crate::agent::session_actor::RuntimeStopReason::Superseded,
    )
    .await
    {
        Ok(outcome) => outcome.was_active,
        Err(error) => {
            return fail_work_session_launch(
                emitter,
                sessions,
                &run_id,
                None,
                format!("Failed to stop the previous Work actor: {error}"),
            )
            .await;
        }
    };

    // Register only after the old actor has stopped. Its exit cleanup is
    // allowed to revoke its own lease without being able to touch this one.
    let (bridge_port, bridge_token) =
        crate::work::internal_bridge::register_session_token_with_proxy(
            &bridge_info.work_run_id,
            bridge_info.workspace_id.as_deref().unwrap_or(""),
            bridge_info.task_id.as_deref(),
            bridge_info.execution_context,
            bridge_info.proxy_url.clone(),
        )
        .await
        .map_err(|error| format!("Failed to register the Work bridge: {error}"))?;
    if let Err(error) = launch_trace.record(WorkRuntimeLaunchStage::BridgeRegistered) {
        crate::work::internal_bridge::revoke_session_token(&bridge_token).await;
        return Err(error.to_string());
    }

    let mut extra_env = HashMap::new();
    extra_env.insert(
        "AGENTCABIN_WORK_BRIDGE_PORT".to_string(),
        bridge_port.to_string(),
    );
    extra_env.insert(
        "AGENTCABIN_WORK_BRIDGE_TOKEN".to_string(),
        bridge_token.clone(),
    );
    extra_env.extend(work_proxy_env);

    let resumes_existing_session = session_persistence_enabled
        && (matches!(&session_mode, SessionMode::Resume | SessionMode::Continue)
            || session_id.is_some()
            || run.session_id.is_some());
    let cmd_tx = match adapter
        .spawn_session_actor(
            Arc::clone(emitter),
            sessions.clone(),
            crate::work::runtime::WorkRuntimeLaunchRequest {
                run: run.clone(),
                session_mode: session_mode.clone(),
                session_id,
                permission_mode_override: permission_mode_override.map(str::to_string),
                capabilities: caps,
                desktop_use_enabled: crate::work::desktop_operator::is_enabled(),
                bridge: bridge_info.clone(),
                extra_env,
                context_plan: context_plan.clone(),
                launch_overrides,
            },
            cancel_token.clone(),
        )
        .await
    {
        Ok(sender) => {
            launch_trace
                .record(WorkRuntimeLaunchStage::ActorSpawned)
                .map_err(String::from)?;
            debug_assert!(launch_trace.is_complete());
            sender
        }
        Err(error) => {
            return fail_work_session_launch(
                emitter,
                sessions,
                &run_id,
                Some(&bridge_token),
                error,
            )
            .await;
        }
    };

    let brand_new = matches!(&session_mode, SessionMode::New) && !resumes_existing_session;
    let initial_text = initial_message
        .or_else(|| brand_new.then(|| run.prompt.clone()))
        .filter(|text| !text.trim().is_empty());
    if let Some(text) = initial_text {
        let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
        if cmd_tx
            .send(ActorCommand::SendMessage {
                text,
                attachments: attachments.unwrap_or_default(),
                skills: skills.unwrap_or_default(),
                work_context_plan: Some(context_plan.clone()),
                reply: reply_tx,
            })
            .await
            .is_err()
        {
            return fail_work_session_launch(
                emitter,
                sessions,
                &run_id,
                Some(&bridge_token),
                "Work actor died before accepting the initial message".to_string(),
            )
            .await;
        }
        // The actor may still be completing the runtime handshake when the command is
        // queued. Do not make the Tauri command wait for that handshake: the frontend can
        // attach to the run immediately, while the durable bus carries session_init and
        // progress. Keep observing the reply in the background, though, so a provider
        // that fails before persisting its own failure cannot leave the run in spawning.
        let reply_emitter = Arc::clone(emitter);
        let reply_sessions = sessions.clone();
        let reply_run_id = run_id.clone();
        let reply_bridge_token = bridge_token.clone();
        tokio::spawn(async move {
            let failure = match reply_rx.await {
                Ok(Ok(())) => None,
                Ok(Err(error)) => Some(error),
                Err(_) => Some("Work actor dropped the initial message reply".to_string()),
            };
            if let Some(error) = failure {
                let _ = fail_work_session_launch(
                    &reply_emitter,
                    &reply_sessions,
                    &reply_run_id,
                    Some(&reply_bridge_token),
                    error,
                )
                .await;
            }
        });
    } else {
        storage::runs::update_status(&run_id, RunStatus::Idle, None, None).ok();
        emit_state(emitter, &run_id, "idle", None);
    }

    Ok(())
}

#[allow(clippy::too_many_arguments)]
pub(crate) async fn start_session_impl(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    spawn_locks: &SpawnLocks,
    cancel_token: &CancellationToken,
    run_id: String,
    mode: Option<SessionMode>,
    session_id: Option<String>,
    initial_message: Option<String>,
    attachments: Option<Vec<AttachmentData>>,
    platform_id: Option<String>,
    permission_mode_override: Option<String>,
    skills: Option<Vec<CodexSkillRef>>,
) -> Result<(), String> {
    start_session_impl_with_overrides(
        emitter,
        sessions,
        spawn_locks,
        cancel_token,
        run_id,
        mode,
        session_id,
        initial_message,
        attachments,
        platform_id,
        permission_mode_override,
        skills,
        None,
    )
    .await
}

#[allow(clippy::too_many_arguments)]
pub(crate) async fn start_session_impl_with_overrides(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    spawn_locks: &SpawnLocks,
    cancel_token: &CancellationToken,
    run_id: String,
    mode: Option<SessionMode>,
    session_id: Option<String>,
    initial_message: Option<String>,
    attachments: Option<Vec<AttachmentData>>,
    platform_id: Option<String>,
    permission_mode_override: Option<String>,
    skills: Option<Vec<CodexSkillRef>>,
    launch_overrides: Option<crate::work::runtime::WorkLaunchOverrides>,
) -> Result<(), String> {
    let mut run =
        storage::runs::get_run(&run_id).ok_or_else(|| format!("Run {} not found", run_id))?;
    let user_settings = storage::settings::get_user_settings();
    if let Some(model) =
        storage::settings::resolve_model_for_agent(&user_settings, &run.agent, run.model.as_deref())
    {
        if launch_overrides
            .as_ref()
            .is_some_and(|o| o.forbid_model_fallback)
        {
            if let Some(req) = launch_overrides.as_ref().and_then(|o| o.model.as_deref()) {
                if model != req {
                    return Err(format!(
                        "Model fallback forbidden: requested '{req}' but resolved to '{model}'"
                    ));
                }
            }
        }
        let model = if run.agent == "pi" && !model.contains('/') {
            if let Some(pid) = user_settings
                .agent_provider_bindings
                .as_ref()
                .map(|b| &b.pi)
                .filter(|b| b.mode == "custom")
                .and_then(|b| b.provider_id.as_deref())
                .filter(|id| !id.trim().is_empty())
            {
                format!("{}/{}", pid, model)
            } else {
                model
            }
        } else {
            model
        };
        if run.model.as_deref() != Some(model.as_str()) {
            log::debug!(
                "[session_dispatch] replacing stale managed model for run {}: {:?} → {}",
                run_id,
                run.model,
                model
            );
            storage::runs::update_run_model(&run_id, &model)?;
            run.model = Some(model);
        }
    } else if launch_overrides
        .as_ref()
        .is_some_and(|o| o.forbid_model_fallback)
    {
        if let Some(req) = launch_overrides.as_ref().and_then(|o| o.model.as_deref()) {
            return Err(format!(
                "Model fallback forbidden: requested '{req}' could not be resolved for agent '{}'",
                run.agent
            ));
        }
    }

    // --- WORK HARNESS DISPATCH (First-Level Authority) ---
    // If this is a Work session, it enters Pi Work Runtime directly.
    // It NEVER falls through to Code provider dispatch (Grok/Claude/Codex/Pi).
    if run.app_mode == crate::work::models::AppMode::Work {
        crate::work::profile::ensure_enabled()?;
        let adapter =
            crate::work::runtime::get_pi_work_runtime(&run.agent).map_err(String::from)?;
        return start_work_session_actor(
            emitter,
            sessions,
            spawn_locks,
            cancel_token,
            run,
            mode,
            session_id,
            initial_message,
            attachments,
            permission_mode_override.as_deref(),
            skills,
            adapter,
            launch_overrides,
        )
        .await;
    }

    // --- CODE MODE PROVIDER DISPATCH ---
    if run.agent == "dsh" {
        return Err("DeepSeek Harness (DSH) runtime has been removed and cannot be started. Please use Pi Agent.".to_string());
    }

    if run.agent == "grok" {
        return start_grok_session(
            emitter,
            sessions,
            spawn_locks,
            cancel_token,
            run,
            mode,
            session_id,
            initial_message,
            attachments,
            permission_mode_override,
            skills,
        )
        .await;
    }

    if run.agent != "pi" {
        return super::session::start_session_impl(
            emitter,
            sessions,
            spawn_locks,
            cancel_token,
            run_id,
            mode,
            session_id,
            initial_message,
            attachments,
            platform_id,
            permission_mode_override,
            skills,
        )
        .await;
    }

    let _guard = spawn_locks.acquire(&run_id).await;
    if run.resolved_execution_path() != ExecutionPath::SessionActor {
        return Err(format!(
            "Pi RPC requires execution_path=session_actor for run {}",
            run_id
        ));
    }
    if run.remote_host_name.is_some() || run.remote_cwd.is_some() {
        return Err("Pi RPC session transport does not support remote hosts yet".to_string());
    }

    let session_mode = mode.unwrap_or_default();
    if matches!(&session_mode, SessionMode::Fork) {
        return Err(
            "Fork mode not supported in start_session — use fork_session command instead"
                .to_string(),
        );
    }

    let (settings, mut extra_env) =
        pi_launch_context(&run, permission_mode_override.as_deref()).await?;
    let resume_session_id = match &session_mode {
        SessionMode::Resume | SessionMode::Continue => {
            if settings.no_session_persistence {
                return Err("Cannot resume: Pi session persistence is disabled".to_string());
            }
            Some(
                session_id
                    .or_else(|| run.session_id.clone())
                    .ok_or_else(|| "Pi session_id is required for resume/continue".to_string())?,
            )
        }
        SessionMode::New => {
            if settings.no_session_persistence {
                None
            } else {
                // Reopening an existing run commonly arrives as mode=New with an
                // explicit follow-up message. Resume the persisted Pi conversation.
                session_id.or_else(|| run.session_id.clone())
            }
        }
        SessionMode::Fork => unreachable!(),
    };

    log::debug!(
        "[session_dispatch] Pi start: run_id={}, mode={:?}, resume={:?}, platform={:?}, permission_override={:?}",
        run_id,
        session_mode,
        resume_session_id,
        platform_id,
        permission_mode_override
    );

    emit_state(emitter, &run_id, "spawning", None);
    storage::runs::update_status(&run_id, RunStatus::Running, None, None).ok();

    let had_session = super::session::stop_actor(
        sessions,
        &run_id,
        crate::agent::session_actor::RuntimeStopReason::Superseded,
    )
    .await?
    .was_active;
    if had_session {
        log::debug!(
            "[session_dispatch] replaced existing Pi actor for run_id={}",
            run_id
        );
    }

    // Register the Code Browser Runtime only after the previous actor has
    // stopped. `pi_launch_context` prepares the shared adapter and ledger
    // directory, but registering here prevents stop/replace cleanup from
    // revoking the fresh token before the new Pi actor starts.
    if extra_env
        .get("AGENTCABIN_BROWSER_ENABLED")
        .map(String::as_str)
        == Some("1")
    {
        let browser_run_dir = storage::run_dir(&run.id).join("browser");
        let (browser_port, browser_token) =
            crate::browser_runtime::register_session(&run.id, &browser_run_dir).await?;
        extra_env.insert(
            "AGENTCABIN_BROWSER_BRIDGE_PORT".to_string(),
            browser_port.to_string(),
        );
        extra_env.insert("AGENTCABIN_BROWSER_BRIDGE_TOKEN".to_string(), browser_token);
    }
    if extra_env
        .get("AGENTCABIN_CODE_CONNECTOR_ENABLED")
        .map(String::as_str)
        == Some("1")
    {
        let (connector_port, connector_token) =
            match crate::code_connector_runtime::register_session(&run.id).await {
                Ok(value) => value,
                Err(error) => {
                    // Browser registration above may already have succeeded;
                    // do not leave that session lease behind on a connector
                    // bridge startup failure.
                    crate::browser_runtime::revoke_session(&run.id).await;
                    return Err(error);
                }
            };
        extra_env.insert(
            "AGENTCABIN_CODE_CONNECTOR_BRIDGE_PORT".to_string(),
            connector_port.to_string(),
        );
        extra_env.insert(
            "AGENTCABIN_CODE_CONNECTOR_BRIDGE_TOKEN".to_string(),
            connector_token,
        );
    }
    if run.app_mode == crate::work::models::AppMode::Code
        && crate::work::desktop_operator::is_enabled()
    {
        let (desktop_port, desktop_token) =
            match crate::desktop_runtime::register_session(&run.id).await {
                Ok(value) => value,
                Err(error) => {
                    crate::browser_runtime::revoke_session(&run.id).await;
                    crate::code_connector_runtime::revoke_session(&run.id).await;
                    return Err(error);
                }
            };
        extra_env.insert(
            "AGENTCABIN_DESKTOP_BRIDGE_PORT".to_string(),
            desktop_port.to_string(),
        );
        extra_env.insert("AGENTCABIN_DESKTOP_BRIDGE_TOKEN".to_string(), desktop_token);
    }

    let resumes_existing_session = resume_session_id.is_some();
    let cmd_tx = match pi_session_actor::spawn_actor(
        Arc::clone(emitter),
        sessions.clone(),
        run_id.clone(),
        run.cwd.clone(),
        &settings,
        resume_session_id,
        extra_env,
        cancel_token.clone(),
    )
    .await
    {
        Ok(sender) => sender,
        Err(error) => {
            crate::browser_runtime::revoke_session(&run_id).await;
            crate::code_connector_runtime::revoke_session(&run_id).await;
            crate::desktop_runtime::revoke_session(&run_id).await;
            storage::runs::update_status(&run_id, RunStatus::Failed, None, Some(error.clone()))
                .ok();
            emit_state(emitter, &run_id, "failed", Some(error.clone()));
            return Err(error);
        }
    };

    let brand_new = matches!(&session_mode, SessionMode::New) && !resumes_existing_session;
    let initial_text = initial_message
        .or_else(|| brand_new.then(|| run.prompt.clone()))
        .filter(|text| !text.trim().is_empty());
    if let Some(text) = initial_text {
        let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
        cmd_tx
            .send(ActorCommand::SendMessage {
                text,
                attachments: attachments.unwrap_or_default(),
                skills: skills.unwrap_or_default(),
                work_context_plan: None,
                reply: reply_tx,
            })
            .await
            .map_err(|_| "Pi actor died before accepting the initial message".to_string())?;
        reply_rx
            .await
            .map_err(|_| "Pi actor dropped the initial message reply".to_string())??;
    } else {
        storage::runs::update_status(&run_id, RunStatus::Idle, None, None).ok();
        emit_state(emitter, &run_id, "idle", None);
    }

    Ok(())
}

#[allow(clippy::too_many_arguments)]
pub async fn start_session(
    emitter: State<'_, Arc<BroadcastEmitter>>,
    sessions: State<'_, ActorSessionMap>,
    spawn_locks: State<'_, SpawnLocks>,
    cancel_token: State<'_, CancellationToken>,
    run_id: String,
    mode: Option<SessionMode>,
    session_id: Option<String>,
    initial_message: Option<String>,
    attachments: Option<Vec<AttachmentData>>,
    platform_id: Option<String>,
    permission_mode_override: Option<String>,
    skills: Option<Vec<CodexSkillRef>>,
) -> Result<(), String> {
    start_session_impl(
        emitter.inner(),
        sessions.inner(),
        spawn_locks.inner(),
        cancel_token.inner(),
        run_id,
        mode,
        session_id,
        initial_message,
        attachments,
        platform_id,
        permission_mode_override,
        skills,
    )
    .await
}

pub async fn send_session_message(
    emitter: State<'_, Arc<BroadcastEmitter>>,
    sessions: State<'_, ActorSessionMap>,
    run_id: String,
    message: String,
    attachments: Option<Vec<AttachmentData>>,
    skills: Option<Vec<CodexSkillRef>>,
) -> Result<(), String> {
    // If this is a Work mode run, re-assemble and refresh the WorkContextPlan for the new turn (fail-closed)
    let mut work_context_plan = None;
    if let Some(run) = storage::runs::get_run(&run_id) {
        if run.app_mode == crate::work::models::AppMode::Work {
            let plan = assemble_work_context_plan_for_turn(&run, &message).await?;
            crate::work::context::save(&run_id, &plan).map_err(|e| {
                format!("Work Context Plan persistence or security validation failed: {e}")
            })?;

            emitter.persist_and_emit(
                &run_id,
                &crate::models::BusEvent::WorkContextPlanUpdated {
                    run_id: run_id.clone(),
                    plan: plan.clone(),
                },
            );
            work_context_plan = Some(plan);
        }
    }

    let cmd_tx = get_cmd_tx(&sessions, &run_id).await?;
    let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
    cmd_tx
        .send(ActorCommand::SendMessage {
            text: message,
            attachments: attachments.unwrap_or_default(),
            skills: skills.unwrap_or_default(),
            work_context_plan,
            reply: reply_tx,
        })
        .await
        .map_err(|_| "Actor dead".to_string())?;
    reply_rx
        .await
        .map_err(|_| "Actor dropped reply".to_string())??;
    Ok(())
}

pub async fn steer_session_message(
    sessions: State<'_, ActorSessionMap>,
    run_id: String,
    message: String,
    attachments: Option<Vec<AttachmentData>>,
) -> Result<(), String> {
    let cmd_tx = get_cmd_tx(&sessions, &run_id).await?;
    let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
    cmd_tx
        .send(ActorCommand::SteerMessage {
            text: message,
            attachments: attachments.unwrap_or_default(),
            reply: reply_tx,
        })
        .await
        .map_err(|_| "Actor dead".to_string())?;
    reply_rx
        .await
        .map_err(|_| "Actor dropped reply".to_string())??;
    Ok(())
}

pub async fn cancel_session_turn(
    sessions: State<'_, ActorSessionMap>,
    run_id: String,
) -> Result<(), String> {
    super::session::cancel_session_turn(sessions, run_id).await
}

pub(crate) async fn stop_session_impl(
    emitter: &Arc<BroadcastEmitter>,
    sessions: &ActorSessionMap,
    spawn_locks: &SpawnLocks,
    run_id: String,
) -> Result<(), String> {
    super::session::stop_session_impl(emitter, sessions, spawn_locks, run_id).await
}

pub async fn stop_session(
    emitter: State<'_, Arc<BroadcastEmitter>>,
    sessions: State<'_, ActorSessionMap>,
    spawn_locks: State<'_, SpawnLocks>,
    run_id: String,
) -> Result<(), String> {
    stop_session_impl(
        emitter.inner(),
        sessions.inner(),
        spawn_locks.inner(),
        run_id,
    )
    .await
}

pub async fn send_session_control(
    sessions: State<'_, ActorSessionMap>,
    run_id: String,
    subtype: String,
    params: Option<serde_json::Value>,
) -> Result<serde_json::Value, String> {
    let cmd_tx = get_cmd_tx(&sessions, &run_id).await?;
    let mut request = serde_json::json!({ "subtype": subtype });
    if let Some(params) = params {
        if let Some(object) = params.as_object() {
            for (key, value) in object {
                request[key] = value.clone();
            }
        }
    }

    let (reply_tx, reply_rx) = tokio::sync::oneshot::channel();
    cmd_tx
        .send(ActorCommand::SendControl {
            request,
            reply: reply_tx,
        })
        .await
        .map_err(|_| "Actor dead".to_string())?;
    let (request_id, response_rx) = reply_rx
        .await
        .map_err(|_| "Actor dropped reply".to_string())??;

    match tokio::time::timeout(std::time::Duration::from_secs(10), response_rx).await {
        Ok(Ok(response)) => Ok(response),
        Ok(Err(_)) => Err(format!(
            "Control response channel closed for request {}",
            request_id
        )),
        Err(_) => Err(format!(
            "Timeout waiting for control response {}",
            request_id
        )),
    }
}

#[cfg(test)]
mod tests {
    use async_trait::async_trait;
    use std::sync::{Arc, Mutex};

    use super::{normalize_grok_permission_mode, WorkBridgeLaunchInfo};

    #[derive(Debug, Clone)]
    struct FakeWorkRuntimeAdapter {
        events: Arc<Mutex<Vec<&'static str>>>,
    }

    #[async_trait]
    impl crate::work::runtime::WorkRuntimeAdapter for FakeWorkRuntimeAdapter {
        fn provider(&self) -> crate::agent::capability_resolver::RuntimeProviderKind {
            crate::agent::capability_resolver::RuntimeProviderKind::Codex
        }

        fn capabilities(&self) -> crate::work::runtime::WorkRuntimeCapabilities {
            crate::work::runtime::WorkRuntimeCapabilities::default()
        }

        fn session_persistence_enabled(
            &self,
            _run: &crate::models::RunMeta,
        ) -> Result<bool, crate::work::runtime::WorkRuntimeError> {
            Ok(false)
        }

        async fn prepare_runtime(
            &self,
            context: &crate::work::runtime::WorkRuntimePrepareContext,
        ) -> Result<(), crate::work::runtime::WorkRuntimeError> {
            assert_eq!(
                context.run.app_mode,
                crate::work::models::AppMode::Work,
                "the generic Work preparation phase must preserve Work authority"
            );
            assert_eq!(
                context.capabilities.runtime,
                crate::agent::capability_resolver::RuntimeProviderKind::Codex
            );
            assert!(!context.paths.work_mcp_config_path().exists());
            self.events.lock().unwrap().push("prepare");
            Ok(())
        }

        async fn spawn_session_actor(
            &self,
            _emitter: Arc<crate::web_server::broadcaster::BroadcastEmitter>,
            _sessions: crate::agent::adapter::ActorSessionMap,
            _request: crate::work::runtime::WorkRuntimeLaunchRequest,
            _cancel_token: tokio_util::sync::CancellationToken,
        ) -> Result<tokio::sync::mpsc::Sender<crate::agent::session_actor::ActorCommand>, String>
        {
            self.events.lock().unwrap().push("spawn");
            Ok(tokio::sync::mpsc::channel(1).0)
        }
    }

    fn fake_work_run() -> crate::models::RunMeta {
        crate::models::RunMeta {
            id: "fake-work-run".to_string(),
            prompt: "test".to_string(),
            cwd: "/tmp".to_string(),
            agent: "fake".to_string(),
            code_standalone_task: false,
            app_mode: crate::work::models::AppMode::Work,
            agent_target: None,
            workspace_id: None,
            work_task_id: None,
            work_run_id: None,
            work_execution_context: None,
            work_preset: None,
            auth_mode: "default".to_string(),
            status: crate::models::RunStatus::Pending,
            started_at: "2026-08-15T00:00:00Z".to_string(),
            ended_at: None,
            exit_code: None,
            error_message: None,
            session_id: None,
            result_subtype: None,
            model: None,
            effort: None,
            permission_mode: None,
            parent_run_id: None,
            continuation_context: None,
            name: None,
            remote_host_name: None,
            remote_cwd: None,
            remote_host_snapshot: None,
            platform_id: None,
            platform_base_url: None,
            source: None,
            cli_import_watermark: None,
            cli_session_path: None,
            cli_usage_incomplete: None,
            deleted_at: None,
            no_session_persistence: false,
            execution_path: None,
            conversation_ref: None,
            codex_process_seq: None,
            codex_imported_rollouts: None,
            pinned: None,
            archived: None,
            unread: None,
        }
    }

    #[test]
    fn pi_launch_prefers_conversation_effort_over_profile_or_project_defaults() {
        let mut run = fake_work_run();
        run.agent = "pi".to_string();
        run.app_mode = crate::work::models::AppMode::Code;
        run.effort = Some("high".to_string());

        let settings = super::pi_adapter_settings(&run, None);

        assert_eq!(settings.effort.as_deref(), Some("high"));
    }

    #[tokio::test]
    async fn generic_work_preparation_delegates_package_provisioning_to_selected_adapter() {
        let temp = tempfile::tempdir().unwrap();
        let paths = crate::work::paths::WorkPaths::new(temp.path().join("work-data"));
        let run = fake_work_run();
        let capabilities = crate::agent::capability_resolver::EffectiveCapabilities {
            app_mode: crate::work::models::AppMode::Work,
            runtime: crate::agent::capability_resolver::RuntimeProviderKind::Codex,
            run_id: run.id.clone(),
            managed_home: temp.path().join("codex-home"),
            managed_runtime_dir: temp.path().join("codex-runtime"),
            enabled_skills: Vec::new(),
            mcp_servers: Vec::new(),
            connectors: Vec::new(),
            browser_enabled: false,
            browser_use_enabled: false,
            browser_config: None,
            allowed_tools: Vec::new(),
            disallowed_tools: Vec::new(),
            prohibited_discovery_paths: Vec::new(),
            detected_prohibited_paths: Vec::new(),
            diagnostics: Vec::new(),
            strict_mode: true,
        };
        let events = Arc::new(Mutex::new(Vec::new()));
        let adapter = FakeWorkRuntimeAdapter {
            events: Arc::clone(&events),
        };

        super::prepare_work_runtime(
            &adapter,
            crate::work::runtime::WorkRuntimePrepareContext {
                paths: paths.clone(),
                run,
                capabilities: capabilities.clone(),
                context_plan: None,
            },
        )
        .await
        .unwrap();

        assert_eq!(*events.lock().unwrap(), vec!["prepare"]);
        assert!(capabilities
            .managed_runtime_dir
            .join("config.toml")
            .is_file());
        assert!(!paths.work_extensions_dir().exists());
        assert!(!paths.work_mcp_config_path().exists());
    }

    #[test]
    fn work_bridge_launch_info_is_runtime_neutral_and_fail_closed() {
        let mut standalone = fake_work_run();
        standalone.work_run_id = None;
        let info =
            WorkBridgeLaunchInfo::from_run(&standalone, Some("http://127.0.0.1:7897".to_string()))
                .unwrap();
        assert_eq!(info.work_run_id, standalone.id);
        assert_eq!(info.workspace_id, None);
        assert_eq!(info.task_id, None);
        assert_eq!(info.proxy_url.as_deref(), Some("http://127.0.0.1:7897"));

        standalone.workspace_id = Some("workspace-chat".to_string());
        let info = WorkBridgeLaunchInfo::from_run(&standalone, None).unwrap();
        assert_eq!(info.workspace_id.as_deref(), Some("workspace-chat"));
        assert_eq!(info.task_id, None);

        standalone.workspace_id = Some("workspace-1".to_string());
        standalone.work_task_id = Some("task-1".to_string());
        standalone.work_run_id = Some("work-run-1".to_string());
        standalone.work_execution_context = Some(crate::work::models::ExecutionContext::Attended);
        let info = WorkBridgeLaunchInfo::from_run(&standalone, None).unwrap();
        assert_eq!(info.work_run_id, "work-run-1");
        assert_eq!(info.workspace_id.as_deref(), Some("workspace-1"));
        assert_eq!(info.task_id.as_deref(), Some("task-1"));
        assert_eq!(
            info.execution_context,
            crate::work::models::ExecutionContext::Attended
        );

        standalone.work_run_id = None;
        let info = WorkBridgeLaunchInfo::from_run(&standalone, None).unwrap();
        assert_eq!(info.work_run_id, standalone.id);
    }

    #[test]
    fn accepts_grok_permission_mode_overrides() {
        for mode in ["default", "acceptEdits", "bypassPermissions"] {
            assert_eq!(
                normalize_grok_permission_mode(Some(mode.to_string())).unwrap(),
                Some(mode.to_string())
            );
        }
    }

    #[test]
    fn rejects_unknown_grok_permission_mode_overrides() {
        let error = normalize_grok_permission_mode(Some("not-a-mode".to_string())).unwrap_err();
        assert!(error.contains("Unsupported Grok permission mode"));
    }

    #[test]
    fn workspace_chat_is_not_standalone() {
        let mut meta = fake_work_run();
        meta.workspace_id = Some("ws-test".to_string());
        meta.work_task_id = None;
        let scope = crate::work::models::WorkScope::from_meta(&meta);
        assert!(!scope.is_standalone());
        assert!(!scope.is_automation());
        assert_eq!(scope.workspace_id.as_deref(), Some("ws-test"));
        assert_eq!(scope.automation_task_id, None);
    }

    #[test]
    fn automation_run_uses_same_id_as_run_meta() {
        let mut meta = fake_work_run();
        meta.workspace_id = Some("ws-test".to_string());
        meta.work_task_id = Some("task-1".to_string());
        meta.work_run_id = None;
        let info = WorkBridgeLaunchInfo::from_run(&meta, None).unwrap();
        assert_eq!(info.work_run_id, meta.id);
        assert_eq!(info.task_id.as_deref(), Some("task-1"));
    }

    #[test]
    fn missing_task_id_is_valid_for_interactive_work() {
        use crate::work::runtime::pi::PiWorkRuntimeAdapter;

        let adapter = PiWorkRuntimeAdapter;
        let mut meta = fake_work_run();
        meta.workspace_id = Some("ws-test".to_string());
        meta.work_task_id = None;
        meta.work_run_id = None;
        meta.work_execution_context = None;

        // In the single-identity architecture, interactive workspace runs do not require task_id
        assert!(adapter.validate_work_run(&meta).is_ok());
    }
}
